brew 'bat'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'htop'
brew 'lua-language-server'
brew 'mise'
brew 'neovim'
brew 'node'
brew 'ripgrep'
brew 'stylua'
brew 'yarn'

cask 'firefox'
cask 'font-jetbrains-mono-nerd-font'
cask 'google-chrome'
cask 'ghostty'
