#!/usr/bin/env bash

echo "Installing homebrew..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/opt/homebrew/bin/brew shellenv)"
brew bundle >> /dev/null
brew cleanup >> /dev/null

echo "Installing ohmyzsh..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
ln -sfn "$PWD/.zshrc" "$HOME/.zshrc"

echo "Configuring macOS settings..."
sh .macos

echo "Configuring git..."
git config --global commit.gpgsign true
git config --global core.editor nvim
git config --global core.ignorecase false
git config --global gpg.format ssh
git config --global pull.rebase true
git config --global fetch.prune true
git config --global init.defaultBranch master
git config --global user.email hvandevliert@icloud.com
git config --global user.name "Hugo van de Vliert"
git config --global user.signingkey "$HOME/.ssh/id_ed25519.pub"

# delta settings
git config --global core.pager 'delta --paging always'
git config --global interactive.diffFilter 'delta --color-only'
git config --global delta.navigate true
git config --global delta.hyperlinks true
git config --global delta.keep-plus-minus-markers false
git config --global delta.blame-palette normal
git config --global delta.blame-format "{commit:<8} {author:<15.15} {timestamp:<16}"
git config --global delta.blame-timestamp-output-format "%F %R"

mkdir -p "$HOME/.config"

echo "Configuring ghostty..."
ln -sfn "$PWD/.config/ghostty" "$HOME/.config/ghostty"

echo "Configuring neovim..."
ln -sfn "$PWD/nvim" "$HOME/.config/nvim"

echo "Configuring ssh..."
mkdir -p "$HOME/.ssh"
ln -sfn "$PWD/.ssh/config" "$HOME/.ssh/config"

echo "Configuring launch agent that remaps Caps Lock to Escape..."
mkdir -p ~/Library/LaunchAgents
cp "$PWD/escape-map.plist" ~/Library/LaunchAgents/custom.escape-map.plist
launchctl load -w ~/Library/LaunchAgents/custom.escape-map.plist

echo "Configuring launch agent that preloads ssh keys from keychain..."
cp "$PWD/ssh-add.plist" ~/Library/LaunchAgents/custom.ssh-add.plist
launchctl load -w ~/Library/LaunchAgents/custom.ssh-add.plist

echo "Installation complete! Please reboot your machine."
