#!/usr/bin/env bash

# Assumes a recent version of ./setup is executed at least once.

echo "Updating brew packages..."
brew bundle --no-lock >> /dev/null
brew cleanup >> /dev/null

echo "Updating vim plugins..."
vim -Esu "$HOME/.vimrc" +PlugInstall +PlugUpdate +qall

echo "Updating ohmyzsh..."
"$ZSH/tools/upgrade.sh" >> /dev/null

echo "Update complete!"
